<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.micronaut.platform</groupId>
    <artifactId>micronaut-parent</artifactId>
    <version>5.0.6</version>
  </parent>

  <groupId>com.hearthworth</groupId>
  <artifactId>hearthworth-parent</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>
  <name>hearthworth</name>
  <description>Hearth Worth multi-module application</description>

  <licenses>
    <license>
      <name>GNU General Public License, Version 3.0</name>
      <url>https://www.gnu.org/licenses/gpl-3.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <modules>
    <module>core</module>
    <module>app</module>
  </modules>

  <properties>
    <revision>0.0.1-SNAPSHOT</revision>
    <jdk.version>25</jdk.version>
    <release.version>25</release.version>
    <micronaut.version>5.0.6</micronaut.version>
    <micronaut.aot.enabled>false</micronaut.aot.enabled>
    <micronaut.aot.packageName>com.hearthworth.aot.generated</micronaut.aot.packageName>
    <micronaut.runtime>netty</micronaut.runtime>
    <exec.mainClass>com.hearthworth.app.Application</exec.mainClass>
  </properties>

</project>