micronaut.application.name=core

# --- Application ---
app.version=0.0.1
logging.level.org=WARN

# --- In-memory user ---
app.security.user.name=${APP_USER_NAME}
app.security.user.password=${APP_USER_PASSWORD}
app.security.user.roles=USER,ADMIN

# --- JWT settings ---
jwt.secret=${JWT_SECRET}
jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}
