micronaut.application.name=core

# --- index.html ---
micronaut.router.static-resources.default.enabled=true
micronaut.router.static-resources.default.mapping=/**
micronaut.router.static-resources.default.paths=classpath:public

# --- Application ---
app.version=0.0.1
logging.level.org=WARN
