micronaut.security.enabled=true
micronaut.security.authentication=bearer
micronaut.security.basic-auth.enabled=false
micronaut.security.reject-not-found=false
micronaut.security.intercept-url-map[0].pattern=/api/**
micronaut.security.intercept-url-map[0].access[0]=isAuthenticated()
micronaut.security.intercept-url-map[1].pattern=/**
micronaut.security.intercept-url-map[1].access[0]=isAnonymous()

micronaut.security.token.jwt.signatures.secret.generator.secret=${jwt.secret}
micronaut.security.token.jwt.signatures.secret.generator.base64=true
micronaut.security.token.jwt.signatures.secret.generator.jws-algorithm=HS512
micronaut.security.token.generator.access-token.expiration=${jwt.expiration-seconds:3600}
